# Generated by Django 5.0.4 on 2024-04-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_card_cardid_alter_card_game_alter_deck_deckid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='game',
            field=models.IntegerField(choices=[(1, 'Unlisted'), (2, 'Magic the Gathering'), (3, 'Pokemon'), (4, 'Yu-Gi-Oh')], default=1),
        ),
        migrations.AlterField(
            model_name='deck',
            name='game',
            field=models.IntegerField(choices=[(1, 'Unlisted'), (2, 'Magic the Gathering'), (3, 'Pokemon'), (4, 'Yu-Gi-Oh')], default=1),
        ),
    ]
