# Generated by Django 5.0.4 on 2024-04-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_card_game_alter_deck_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='cardID',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='deckID',
        ),
    ]
