# Generated by Django 5.0.4 on 2024-04-29 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_card_cardid_remove_deck_deckid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.deck')),
            ],
        ),
    ]
