# Generated by Django 5.0.4 on 2024-04-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_cardindeck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardindeck',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
